### ISSUE TITLE
Drag and drop text crashes the app

### ISSUE THREAD

**Issue by TWiStErRob** [TWiStErRob/net.twisterrob.colorfilters#4]
Repro:
1. Change to Matrix
2. Select some text
3. Drag and drop text to another matrix cell

```
java.lang.NullPointerException: 
  at android.widget.Editor.onDrop (Editor.java:2646)
  at android.widget.TextView.onDragEvent (TextView.java:13384)
  at android.view.View.callDragEventHandler (View.java:24395)
  at android.view.View.dispatchDragEvent (View.java:24383)
  at android.view.ViewGroup.dispatchDragEvent (ViewGroup.java:1689)
  at android.view.ViewGroup.dispatchDragEvent (ViewGroup.java:1689)
  at android.view.ViewGroup.dispatchDragEvent (ViewGroup.java:1689)
  at android.view.ViewGroup.dispatchDragEvent (ViewGroup.java:1689)
  at android.view.ViewGroup.dispatchDragEvent (ViewGroup.java:1689)
  at android.view.ViewGroup.dispatchDragEvent (ViewGroup.java:1689)
  at android.view.ViewGroup.dispatchDragEvent (ViewGroup.java:1689)
  at android.view.ViewGroup.dispatchDragEvent (ViewGroup.java:1689)
  at android.view.ViewGroup.dispatchDragEvent (ViewGroup.java:1689)
  at android.view.ViewGroup.dispatchDragEvent (ViewGroup.java:1689)
  at android.view.ViewGroup.dispatchDragEvent (ViewGroup.java:1689)
  at android.view.ViewGroup.dispatchDragEvent (ViewGroup.java:1689)
  at android.view.ViewRootImpl.handleDragEvent (ViewRootImpl.java:6868)
  at android.view.ViewRootImpl.-wrap12 (Unknown Source)
  at android.view.ViewRootImpl$ViewRootHandler.handleMessage (ViewRootImpl.java:4613)
  at android.os.Handler.dispatchMessage (Handler.java:105)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6938)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:327)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1374)
```

**Comment by TWiStErRob** [comment]
2591
```
    java.lang.ClassCastException: android.widget.Editor$DragLocalState cannot be cast to android.view.View
        at net.twisterrob.colorfilters.android.matrix.OrderComponent$ItemDragListener.onDrag(OrderComponent.java:178)
        at android.view.View.dispatchDragEvent(View.java:21068)
        at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1556)
        at android.view.ViewGroup.notifyChildOfDrag(ViewGroup.java:1587)
        at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1429)
        at android.view.ViewGroup.notifyChildOfDrag(ViewGroup.java:1587)
        at android.view.ViewGroup.onChildVisibilityChanged(ViewGroup.java:1300)
        at android.view.View.setFlags(View.java:11815)
        at android.view.View.setVisibility(View.java:7988)
        at net.twisterrob.colorfilters.android.matrix.MatrixFragment$2.customKeyboardHidden(MatrixFragment.java:92)
        at net.twisterrob.colorfilters.android.keyboard.BaseKeyboardHandler.hideCustomKeyboard(BaseKeyboardHandler.java:41)
        at net.twisterrob.colorfilters.android.keyboard.BaseKeyboardHandler$MyOnFocusChangeListener.onFocusChange(BaseKeyboardHandler.java:136)
        at android.view.View.onFocusChanged(View.java:6254)
        at android.widget.TextView.onFocusChanged(TextView.java:9457)
        at android.widget.EditText.onFocusChanged(EditText.java:203)
        at android.view.View.clearFocusInternal(View.java:6124)
        at android.view.View.unFocus(View.java:6169)
        at android.view.ViewGroup.requestChildFocus(ViewGroup.java:750)
        at android.view.View.handleFocusGainInternal(View.java:5973)
        at android.view.View.requestFocusNoSearch(View.java:9053)
        at android.view.View.requestFocus(View.java:9032)
        at android.view.View.requestFocus(View.java:8999)
        at android.view.View.requestFocus(View.java:8978)
        at android.widget.TextView.onDragEvent(TextView.java:11294)
        at android.view.View.dispatchDragEvent(View.java:21072)
        at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1493)
        at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1505)
        at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1505)
        at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1505)
        at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1505)
        at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1505)
        at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1505)
        at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1505)
        at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1505)
        at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1505)
        at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1505)
        at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1505)
        at android.view.ViewRootImpl.handleDragEvent(ViewRootImpl.java:6434)
        at android.view.ViewRootImpl.access$1400(ViewRootImpl.java:194)
        at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:4281)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:158)
        at android.app.ActivityThread.main(ActivityThread.java:7224)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by TWiStErRob** [comment]
2708
```
 java.lang.ClassCastException: android.widget.Editor$DragLocalState cannot be cast to android.view.View
        at net.twisterrob.colorfilters.android.matrix.OrderComponent$ItemDragListener.onDrag(OrderComponent.kt:159)
        at android.view.View.dispatchDragEvent(View.java:21068)
        at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1556)
        at android.view.ViewGroup.notifyChildOfDrag(ViewGroup.java:1587)
        at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1429)
        at android.view.ViewGroup.notifyChildOfDrag(ViewGroup.java:1587)
        at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1429)
        at android.view.ViewGroup.notifyChildOfDrag(ViewGroup.java:1587)
        at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1429)
        at android.view.ViewGroup.notifyChildOfDrag(ViewGroup.java:1587)
        at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1429)
        at android.view.ViewGroup.notifyChildOfDrag(ViewGroup.java:1587)
        at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1429)
        at android.view.ViewGroup.notifyChildOfDrag(ViewGroup.java:1587)
        at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1429)
        at android.view.ViewGroup.notifyChildOfDrag(ViewGroup.java:1587)
        at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1429)
        at android.view.ViewGroup.notifyChildOfDrag(ViewGroup.java:1587)
        at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1429)
        at android.view.ViewGroup.notifyChildOfDrag(ViewGroup.java:1587)
        at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1429)
        at android.view.ViewGroup.notifyChildOfDrag(ViewGroup.java:1587)
        at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1429)
        at android.view.ViewGroup.notifyChildOfDrag(ViewGroup.java:1587)
        at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1429)
        at android.view.ViewRootImpl.handleDragEvent(ViewRootImpl.java:6434)
        at android.view.ViewRootImpl.access$1400(ViewRootImpl.java:194)
        at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:4281)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:158)
        at android.app.ActivityThread.main(ActivityThread.java:7224)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by TWiStErRob** [comment]
Filtered `onDrag` by a typed local state.
