### ISSUE TITLE
Request storage permissions

### ISSUE THREAD

**Issue by TWiStErRob** [TWiStErRob/net.twisterrob.colorfilters#9]
```
0-21 15:05:04.663 29936-29936/net.twisterrob.colorfilters.debug E/LOGO: /storage/emulated/0/Pictures/colorfilters_logo_512.png: open failed: EACCES (Permission denied)
    java.io.FileNotFoundException: /storage/emulated/0/Pictures/colorfilters_logo_512.png: open failed: EACCES (Permission denied)
        at libcore.io.IoBridge.open(IoBridge.java:452)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:72)
        at net.twisterrob.colorfilters.android.image.LogoWriter.write(LogoWriter.kt:32)
        at net.twisterrob.colorfilters.android.image.LogoWriter.write(LogoWriter.kt:24)
        at net.twisterrob.colorfilters.android.MainActivity.onOptionsItemSelected(MainActivity.kt:151)
```
```
10-21 15:05:59.063 31930-31930/net.twisterrob.colorfilters.debug E/MediaStore: Failed to insert image
    java.lang.SecurityException: Permission Denial: writing com.android.providers.media.MediaProvider uri content://media/external/images/media from pid=31930, uid=10283 requires android.permission.WRITE_EXTERNAL_STORAGE, or grantUriPermission()
        at android.os.Parcel.readException(Parcel.java:1620)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
        at android.content.ContentProviderProxy.insert(ContentProviderNative.java:476)
        at android.content.ContentResolver.insert(ContentResolver.java:1284)
        at android.provider.MediaStore$Images$Media.insertImage(MediaStore.java:986)
        at net.twisterrob.colorfilters.android.MainActivity.renderCurrentView(MainActivity.kt:246)
        at net.twisterrob.colorfilters.android.ColorFilterFragment.onOptionsItemSelected(ColorFilterFragment.kt:71)
```

**Comment by TWiStErRob** [comment]
Replaced WRITE_EXTERNAL_STORAGE with internal storage and ACTION_SEND

**Comment by TWiStErRob** [comment]
Fixed
